const DATA = [
	{
		id: 1,
		name: "Sports",
		routeName: "/sports",
		topics: [
			{
				id: 1,
				name: "Football",
				imageUrl: "football",
				questions: [
					{
						id: 1,
						question:
							"Which player scored the fastest hat-trick in the Premier League?",
						option1: "1. Sadio Mane ",
						option2: "2. Ronaldo",
						option3: "3. Rooney",
						option4: "4. Bale",
						correctOption: 1,
					},
					{
						id: 2,
						question:
							"Which team won the first Premier League title?",
						option1: "1. Liverpool",
						option2: "2. Blackburn Rovers",
						option3: "3. Manchester United",
						option4: "4. Chelsea",
						correctOption: 3,
					},
					{
						id: 3,
						question:
							"The fastest goal scored in Premier League history came in 7.69 seconds. Who scored it?",
						option1: "1. Roberto Firmino",
						option2: "2. Shane Long",
						option3: "3. Peter Crouch",
						option4: "4. Sergio Aguero",
						correctOption: 2,
					},
					{
						id: 4,
						question: "Which country has won the most World Cups?",
						option1: "1. Germany",
						option2: "2. Brazil",
						option3: "3. France",
						option4: "4. Argentina",
						correctOption: 2,
					},
					{
						id: 5,
						question:
							"The record number of World Cup goals is 16, scored by who?",
						option1: "1. Lionel Messi",
						option2: "2. Cristiano Ronadlo",
						option3: "3. Toni Kroos",
						option4: "4. Miroslav Klose",
						correctOption: 4,
					},
					{
						id: 6,
						question:
							"Which Portuguese team did Ronaldo play for before signing for Manchester United?",
						option1: "1. Sporting Lisbon",
						option2: "2. Real Madrid",
						option3: "3. Malmo",
						option4: "4. PSG",
						correctOption: 1,
					},
					{
						id: 7,
						question:
							"Which German multinational sportswear company is Messi an ambassador for?",
						option1: "1. Nike",
						option2: "2. Puma",
						option3: "3. Adidas",
						option4: "4. New Balance",
						correctOption: 3,
					},
					{
						id: 8,
						question:
							"Ronaldo helped Portugal win the European Championship in which year?",
						option1: "1. 2016",
						option2: "2. 2005",
						option3: "3. 2012",
						option4: "4. 2017",
						correctOption: 1,
					},
					{
						id: 9,
						question:
							"Which club has won the most Champions League titles?",
						option1: "1. Bayern Munich",
						option2: "2. Manchester United",
						option3: "3. Real Madrid",
						option4: "4. AC Milan",
						correctOption: 3,
					},
					{
						id: 10,
						question:
							"In video game FIFA 20, team Piemonte Calcio represents which real-life club?",
						option1: "1. FC Barcelona",
						option2: "2. FC Porto",
						option3: "3. Inter Milan",
						option4: "4. Juventus",
						correctOption: 4,
					},
				],
			},
			{
				id: 2,
				name: "Cricket",
				imageUrl: "cricket",
				questions: [
					{
						id: 1,
						question: "Who won the first World Cup, 1975?",
						option1: "1. West Indies ",
						option2: "2. India",
						option3: "3. England",
						option4: "4. New Zealand",
						correctOption: 1,
					},
					{
						id: 2,
						question:
							"How many minutes before play should the umpires take the field?",
						option1: "1. 10min",
						option2: "2. 60min",
						option3: "3. 5min",
						option4: "4. 30min",
						correctOption: 3,
					},
					{
						id: 3,
						question: "What Indian cricketer is called “Zak”?",
						option1: "1. Virat Kohli",
						option2: "2. Zaheer Khan",
						option3: "3. Ishant Sharma",
						option4: "4. Rohit Sharma",
						correctOption: 2,
					},
					{
						id: 4,
						question: "Wankhede stadium is located in?",
						option1: "1. Kanpur",
						option2: "2. Mumbai",
						option3: "3. Chennai",
						option4: "4. Kolkata",
						correctOption: 2,
					},
					{
						id: 5,
						question: "Eden Gardens is located in?",
						option1: "1. Pune",
						option2: "2. Kolkata",
						option3: "3. Delhi",
						option4: "4. Kochi",
						correctOption: 3,
					},
					{
						id: 6,
						question:
							"Who was the captain of the Under-19 Cricket team who won the World Cup in March-2008?",
						option1: "1. Virat Kohli",
						option2: "2. Rohit Sharma",
						option3: "3. MS Dhoni",
						option4: "4. Yuvraj Singh",
						correctOption: 1,
					},
					{
						id: 7,
						question:
							"Yuvraj Singh smashed whom for six sixes in the first Twenty20 world championship?",
						option1: "1. Lasith Malinga",
						option2: "2. Mitchel Starc",
						option3: "3. Stuart Broad",
						option4: "4. James Anderson",
						correctOption: 3,
					},
					{
						id: 8,
						question:
							"Who was named India's Cricketer of the Century?",
						option1: "1. Kapil Dev",
						option2: "2. Sunil Gavaskar",
						option3: "3. MS Dhoni",
						option4: "4. Sachin Tendulkar",
						correctOption: 1,
					},
					{
						id: 9,
						question:
							"What did the commentator say when Dhoni hit the winning six in the 2011 World Cup Finals",
						option1: "1. Sri Lanka have lost the..",
						option2: "2. It's a six!",
						option3: "3. Dhoniii finishes off in style..",
						option4: "4. World Cup belong to India",
						correctOption: 3,
					},
					{
						id: 10,
						question:
							"Who was Player of the Tournament in 2011 World Cup",
						option1: "1. Zaheer Khan",
						option2: "2. Sachin Tendulkar",
						option3: "3. Virat Kohli",
						option4: "4. Yuvraj Singh",
						correctOption: 4,
					},
				],
			},
			{
				id: 3,
				name: "Basketball",
				imageUrl: "basketball",
				questions: [
					{
						id: 1,
						question: "Which team did Kobe Bryant play for?",
						option1: "1. Lakers ",
						option2: "2. Miami Heat",
						option3: "3. Houston Rockets",
						option4: "4. Cavaliers",
						correctOption: 1,
					},
					{
						id: 2,
						question:
							" The first NBA player to win five season MVP awards was?",
						option1: "1. Kevin Durant",
						option2: "2. Bill Russell",
						option3: "3. LeBron James",
						option4: "4. Michael Jordan",
						correctOption: 3,
					},
					{
						id: 3,
						question: "Which team won the first NBA Championship?",
						option1: "1. Cavaliers",
						option2: "2. Rockets",
						option3: "3. Lakers",
						option4: "4. Heat",
						correctOption: 3,
					},
					{
						id: 4,
						question:
							"Physical contact between two players is what kind of foul?",
						option1: "1. Personal foul",
						option2: "2. Flagrant foul",
						option3: "3. Technical foul",
						option4: "4. No Foul",
						correctOption: 1,
					},
					{
						id: 5,
						question: "Kicking a basketball is what kind of foul?",
						option1: "1. No foul",
						option2: "2. Personal foul",
						option3: "3. Flagrant foul",
						option4: "4. Technical foul",
						correctOption: 4,
					},
					{
						id: 6,
						question: "What is one way to legally make a steal?",
						option1: "1. Deflect a pass",
						option2: "2. Yank the ball from the ball-handler",
						option3: "3. Trip the ball-handler",
						option4: "4. Push the opponent",
						correctOption: 1,
					},
					{
						id: 7,
						question: "A free throw is worth…",
						option1: "1. 2 point",
						option2: "2. 3 point",
						option3: "3. 1 point",
						option4: "4. 5 point",
						correctOption: 3,
					},
					{
						id: 8,
						question:
							"There are __ total players on the basketball at one time.",
						option1: "1. 7",
						option2: "2. 6",
						option3: "3. 10",
						option4: "4. 22",
						correctOption: 3,
					},
					{
						id: 9,
						question: "When was basketball made?",
						option1: "1. 1971",
						option2: "2. 1500",
						option3: "3. 1891",
						option4: "4. 1847",
						correctOption: 3,
					},
					{
						id: 10,
						question:
							"What is the highest governing body of basketball?",
						option1: "1. ICC",
						option2: "2. NBA",
						option3: "3. FIFA",
						option4: "4. UEFA",
						correctOption: 2,
					},
				],
			},
			{
				id: 4,
				name: "Olympics",
				imageUrl: "olympic",
				questions: [
					{
						id: 1,
						question:
							"The first winter Olympics was held in which year?",
						option1: "1. 1924 ",
						option2: "2. 1900",
						option3: "3. 1855",
						option4: "4. 1970",
						correctOption: 1,
					},
					{
						id: 2,
						question:
							"The first Summer Olympics was held in which year?",
						option1: "1. 1902",
						option2: "2. 1900",
						option3: "3. 1896",
						option4: "4. 2000",
						correctOption: 3,
					},
					{
						id: 3,
						question:
							"Which Colour represents Asia in Olympics ring?",
						option1: "1. Red",
						option2: "2. Yellow",
						option3: "3. Black",
						option4: "4. Green",
						correctOption: 2,
					},
					{
						id: 4,
						question: "Where did the 2018 Winter Olympics held?",
						option1: "1. South Korea",
						option2: "2. Japan",
						option3: "3. China",
						option4: "4. India",
						correctOption: 1,
					},
					{
						id: 5,
						question:
							"Where is the headquarters of International Olympic Committee situated?",
						option1: "1. Germany",
						option2: "2. Sweden",
						option3: "3. Delhi",
						option4: "4. Switzerland",
						correctOption: 4,
					},
					{
						id: 6,
						question:
							"Who is the present President of International Olympic Committee?",
						option1: "1. Thomas Bach",
						option2: "2. Jacques Rogge",
						option3: "3. Craig Reedie",
						option4: "4. Mukesh Ambani",
						correctOption: 1,
					},
					{
						id: 7,
						question:
							"Who is the first Indian woman to join the International Olympic Committee?",
						option1: "1. Narinder Batra",
						option2: "2. Nita Ambani",
						option3: "3. Karnam Malleswari",
						option4: "4. Narendra Modi",
						correctOption: 2,
					},
					{
						id: 8,
						question:
							"Who is the current president of Indian Olympic committee?",
						option1: "1. Narayana Ramachandran",
						option2: "2. Rajeev Mehta",
						option3: "3. Narinder Batra",
						option4: "4. Nita Ambani",
						correctOption: 3,
					},
					{
						id: 9,
						question:
							"Who was the first Indian woman to ever win an Olympic medal ?",
						option1: "1. Karnam Malleswari",
						option2: "2. Geeta Phogat",
						option3: "3. Mary Kom",
						option4: "4. None of these",
						correctOption: 1,
					},
					{
						id: 10,
						question:
							"Which of the following country was banned in Winter Olympics 2018?",
						option1: "1. North Korea",
						option2: "2. India",
						option3: "3. Russia",
						option4: "4. USA",
						correctOption: 3,
					},
				],
			},
		],
	},
	// {
	// 	id: 2,
	// 	name: "Programming",
	// 	routeName: "/programming",
	// 	topics: [
	// 		{
	// 			id: 1,
	// 			name: "C++",
	// 			imageUrl: "cpp",
	// 		},
	// 		{
	// 			id: 2,
	// 			name: "Python",
	// 			imageUrl: "python",
	// 		},
	// 		{
	// 			id: 3,
	// 			name: "Java",
	// 			imageUrl: "java",
	// 		},
	// 		{
	// 			id: 4,
	// 			name: "CSS",
	// 			imageUrl: "css",
	// 		},
	// 		{
	// 			id: 5,
	// 			name: "HTML",
	// 			imageUrl: "html",
	// 		},
	// 	],
	// },
	// {
	// 	id: 3,
	// 	name: "Technology",
	// 	routeName: "/technology",
	// 	topics: [
	// 		{
	// 			id: 1,
	// 			name: "Football",
	// 			imageUrl: "https://i.ibb.co/ZYW3VTp/brown-brim.png",
	// 		},
	// 		{
	// 			id: 2,
	// 			name: "Cricket",
	// 			imageUrl: "https://i.ibb.co/ypkgK0X/blue-beanie.png",
	// 		},
	// 		{
	// 			id: 3,
	// 			name: "Basketball",
	// 			imageUrl: "https://i.ibb.co/QdJwgmp/brown-cowboy.png",
	// 		},
	// 		{
	// 			id: 4,
	// 			name: "Olympics",
	// 			imageUrl: "https://i.ibb.co/RjBLWxB/grey-brim.png",
	// 		},
	// 		{
	// 			id: 5,
	// 			name: "Olympics",
	// 			imageUrl: "https://i.ibb.co/RjBLWxB/grey-brim.png",
	// 		},
	// 		{
	// 			id: 6,
	// 			name: "Olympics",
	// 			imageUrl: "https://i.ibb.co/RjBLWxB/grey-brim.png",
	// 		},
	// 	],
	// },
	// {
	// 	id: 4,
	// 	name: "Geography",
	// 	routeName: "/geography",
	// 	topics: [
	// 		{
	// 			id: 1,
	// 			name: "Football",
	// 			imageUrl: "https://i.ibb.co/ZYW3VTp/brown-brim.png",
	// 		},
	// 		{
	// 			id: 2,
	// 			name: "Cricket",
	// 			imageUrl: "https://i.ibb.co/ypkgK0X/blue-beanie.png",
	// 		},
	// 		{
	// 			id: 3,
	// 			name: "Basketball",
	// 			imageUrl: "https://i.ibb.co/QdJwgmp/brown-cowboy.png",
	// 		},
	// 		{
	// 			id: 4,
	// 			name: "Olympics",
	// 			imageUrl: "https://i.ibb.co/RjBLWxB/grey-brim.png",
	// 		},
	// 		{
	// 			id: 5,
	// 			name: "Olympics",
	// 			imageUrl: "https://i.ibb.co/RjBLWxB/grey-brim.png",
	// 		},
	// 		{
	// 			id: 6,
	// 			name: "Olympics",
	// 			imageUrl: "https://i.ibb.co/RjBLWxB/grey-brim.png",
	// 		},
	// 	],
	// },
	{
		id: 5,
		name: "India",
		routeName: "/history",
		topics: [
			{
				id: 1,
				name: "History",
				imageUrl: "history",
				questions: [
					{
						id: 1,
						question:
							"Who was the president of INC at the time of independence?",
						option1: "1. Gandhi",
						option2: "2. JB Kripalani",
						option3: "3. Sarojini Naidu",
						option4: "4. None of the above",
						correctOption: 2,
					},
					{
						id: 2,
						question:
							"The national anthem of India ‘Jana Gana Mana’ was first sung at __?",
						option1: "1. Calcutta, 1911",
						option2: "2. Calcutta, 1912",
						option3: "3. Delhi, 1911",
						option4: "4. Mumbai, 1912",
						correctOption: 1,
					},
					{
						id: 3,
						question: "Who is known as Father of Indian Unrest ?",
						option1: "1. Dadabhai Nauroji",
						option2: "2. G. K. Gokhale",
						option3: "3. Mahatma Gandhi",
						option4: "4. Bal Gangadhar Tilak",
						correctOption: 4,
					},
					{
						id: 4,
						question:
							"Who were the first to start a joint stock company to trade with India?",
						option1: "1. Portuguese",
						option2: "2. Dutch",
						option3: "3. French",
						option4: "4. Danish",
						correctOption: 2,
					},
					{
						id: 5,
						question:
							"Who among the following were the first to establish “Printing Press” in India?",
						option1: "1. British",
						option2: "2. Portuguese",
						option3: "3. Dutch",
						option4: "4. French",
						correctOption: 2,
					},
					{
						id: 6,
						question: "Upnishads are books on?",
						option1: "1. Politics",
						option2: "2. Philosophy",
						option3: "3. Medicine",
						option4: "4. Social life",
						correctOption: 2,
					},
					{
						id: 7,
						question: "Where were the hymns of Rigveda composed?",
						option1: "1. Punjab",
						option2: "2. Gujarat",
						option3: "3. Rajasthan",
						option4: "4. Uttar Pradesh",
						correctOption: 1,
					},
					{
						id: 8,
						question:
							"What led to the end of Indus Valley Civilization?",
						option1: "1. Invasion of Aryans",
						option2: "2. Recurrent Floods",
						option3: "3. Earthquakes",
						option4: "4. All the above",
						correctOption: 4,
					},
					{
						id: 9,
						question: "Chanakya was the teacher of?",
						option1: "1. Chandragupta Maurya",
						option2: "2. Ashoka",
						option3: "3. Narendra Modi",
						option4: "4. None of these",
						correctOption: 1,
					},
					{
						id: 10,
						question: "Independence Day of India is on?",
						option1: "1. 15th August",
						option2: "2. 20th March",
						option3: "3. 14th August",
						option4: "4. 1st January",
						correctOption: 1,
					},
				],
			},
			{
				id: 2,
				name: "Geography",
				imageUrl: "geography",
				questions: [
					{
						id: 1,
						question: "Southernmost tip of the Indian mainland is?",
						option1: "1. Delhi",
						option2: "2. Chennai",
						option3: "3. Kanyakumari",
						option4: "4. Kochi",
						correctOption: 3,
					},
					{
						id: 2,
						question:
							"Which one of the following is not a tributary of Indus River?",
						option1: "1. Chenab",
						option2: "2. Beas",
						option3: "3. Ravi",
						option4: "4. Tawi",
						correctOption: 4,
					},
					{
						id: 3,
						question:
							"Botanic Garden of India Republic (BGIR) is located in?",
						option1: "1. Bangalore",
						option2: "2. Kolkata",
						option3: "3. Lucknow",
						option4: "4. Noida",
						correctOption: 4,
					},
					{
						id: 4,
						question:
							"In which of the following states, India’s maximum number of mines producing minerals (excluding minor minerals, petroleum (crude), natural gas and atomic minerals) are located?",
						option1: "1. Gujarat",
						option2: "2. Andhra Pradesh",
						option3: "3. Jharkhand",
						option4: "4. Madhya Pradesh",
						correctOption: 2,
					},
					{
						id: 5,
						question:
							"Which among the following is a riverine (Inland River) port?",
						option1: "1. Chennai",
						option2: "2. Kandla",
						option3: "3. Kolkata",
						option4: "4. Tutikorin",
						correctOption: 3,
					},
					{
						id: 6,
						question:
							"In India, which among the following state has the maximum estimated Uranium Resources?",
						option1: "1. Jharkhand",
						option2: "2. Tamil Nadu",
						option3: "3. Madhya Pradesh",
						option4: "4. Andhra Pradesh",
						correctOption: 4,
					},
					{
						id: 7,
						question:
							"How many members of the United Nations can exercise the Veto Power?",
						option1: "1. 5",
						option2: "2. 3",
						option3: "3. 10",
						option4: "4. 2",
						correctOption: 1,
					},
					{
						id: 8,
						question:
							"Which among the following is a typical Monsoon vegetation in India?",
						option1: "1. Tropical evergreen forests",
						option2: "2. Tropical deciduous forest",
						option3: "3. Tropical thorn forests",
						option4: "4. Sub Tropical evergreen forests",
						correctOption: 2,
					},
					{
						id: 9,
						question:
							"Which of the following pass link the Srinagar to Leh?",
						option1: "1. Mana Pass",
						option2: "2. Rohtas Pass",
						option3: "3. Nathula Pass",
						option4: "4. Zoji La Pass",
						correctOption: 4,
					},
					{
						id: 10,
						question:
							"Which of the following pass has been created by the Indus River?",
						option1: "1. Rohtas Pass",
						option2: "2. Nathula Pass",
						option3: "3. Baralachala Pass",
						option4: "4. Banihal Pass",
						correctOption: 4,
					},
				],
			},
			// {
			// 	id: 3,
			// 	name: "Basketball",
			// 	imageUrl: "https://i.ibb.co/QdJwgmp/brown-cowboy.png",
			// },
			// {
			// 	id: 4,
			// 	name: "Olympics",
			// 	imageUrl: "https://i.ibb.co/RjBLWxB/grey-brim.png",
			// },
			// {
			// 	id: 5,
			// 	name: "Olympics",
			// 	imageUrl: "https://i.ibb.co/RjBLWxB/grey-brim.png",
			// },
			// {
			// 	id: 6,
			// 	name: "Olympics",
			// 	imageUrl: "https://i.ibb.co/RjBLWxB/grey-brim.png",
			// },
		],
	},
];

export default DATA;
